name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: metric
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@fork
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.base.svg
          base: header, activity, community, repositories, metadata

